---
driver:
  name: vagrant
  product_version: 14.1.1

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[datadog::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
      datadog:
        datadog_api_key: '123456'
        datadog_hostname: 'i-barito'
